#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HTTP_PLUGIN_SMOKE_ARTIFACTS_DIR="${AOT_MAF_HTTP_PLUGIN_ARTIFACTS_DIR:-$ROOT_DIR/artifacts/aot-maf-http-plugin}" \
HTTP_PLUGIN_SMOKE_RUNTIME_MODE="aot" \
HTTP_PLUGIN_SMOKE_ORCHESTRATOR="maf" \
HTTP_PLUGIN_SMOKE_GATEWAY_PORT="${AOT_MAF_HTTP_PLUGIN_GATEWAY_PORT:-20049}" \
HTTP_PLUGIN_SMOKE_PROVIDER_PORT="${AOT_MAF_HTTP_PLUGIN_PROVIDER_PORT:-22049}" \
HTTP_PLUGIN_SMOKE_NOTE_KEY="aot-maf-plugin" \
HTTP_PLUGIN_SMOKE_NOTE_CONTENT="from maf aot plugin" \
HTTP_PLUGIN_SMOKE_PUBLISH_AOT="1" \
HTTP_PLUGIN_SMOKE_ENABLE_MAF="1" \
bash "$ROOT_DIR/eng/verify-http-plugin-tool-smoke.sh"
