#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export HTTP_RESPONSES_STREAM_TOOL_SMOKE_ARTIFACTS_DIR="${AOT_NATIVE_HTTP_RESPONSES_STREAM_TOOL_ARTIFACTS_DIR:-$ROOT_DIR/artifacts/aot-native-http-responses-stream-tool}"
export HTTP_RESPONSES_STREAM_TOOL_SMOKE_RUNTIME_MODE="aot"
export HTTP_RESPONSES_STREAM_TOOL_SMOKE_ORCHESTRATOR="native"
export HTTP_RESPONSES_STREAM_TOOL_SMOKE_GATEWAY_PORT="${AOT_NATIVE_HTTP_RESPONSES_STREAM_TOOL_GATEWAY_PORT:-20054}"
export HTTP_RESPONSES_STREAM_TOOL_SMOKE_PROVIDER_PORT="${AOT_NATIVE_HTTP_RESPONSES_STREAM_TOOL_PROVIDER_PORT:-22054}"
export HTTP_RESPONSES_STREAM_TOOL_SMOKE_PUBLISH_AOT="1"
export HTTP_RESPONSES_STREAM_TOOL_SMOKE_ENABLE_MAF="0"

bash "$ROOT_DIR/eng/verify-http-responses-stream-tool-smoke.sh"
