#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export HTTP_RESPONSES_FAILED_SMOKE_ARTIFACTS_DIR="${AOT_MAF_HTTP_RESPONSES_FAILED_ARTIFACTS_DIR:-$ROOT_DIR/artifacts/aot-maf-http-responses-failed}"
export HTTP_RESPONSES_FAILED_SMOKE_RUNTIME_MODE="aot"
export HTTP_RESPONSES_FAILED_SMOKE_ORCHESTRATOR="maf"
export HTTP_RESPONSES_FAILED_SMOKE_GATEWAY_PORT="${AOT_MAF_HTTP_RESPONSES_FAILED_GATEWAY_PORT:-20059}"
export HTTP_RESPONSES_FAILED_SMOKE_PROVIDER_PORT="${AOT_MAF_HTTP_RESPONSES_FAILED_PROVIDER_PORT:-22059}"
export HTTP_RESPONSES_FAILED_SMOKE_PUBLISH_AOT="1"
export HTTP_RESPONSES_FAILED_SMOKE_ENABLE_MAF="1"

bash "$ROOT_DIR/eng/verify-http-responses-failed-smoke.sh"
