#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ARTIFACTS_DIR="$ROOT_DIR/artifacts/aot-maf-ws-approval-outcomes"
rm -rf "$ARTIFACTS_DIR"
mkdir -p "$ARTIFACTS_DIR"

APPROVAL_OUTCOMES_ARTIFACTS_DIR="$ARTIFACTS_DIR" \
APPROVAL_OUTCOMES_RUNTIME_MODE="aot" \
APPROVAL_OUTCOMES_ORCHESTRATOR="maf" \
APPROVAL_OUTCOMES_GATEWAY_PORT="${APPROVAL_OUTCOMES_GATEWAY_PORT:-22137}" \
APPROVAL_OUTCOMES_PROVIDER_PORT="${APPROVAL_OUTCOMES_PROVIDER_PORT:-22138}" \
APPROVAL_OUTCOMES_PUBLISH_AOT=1 \
APPROVAL_OUTCOMES_ENABLE_MAF=1 \
bash "$ROOT_DIR/eng/verify-websocket-approval-outcomes-smoke.sh"
