#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APPROVAL_SMOKE_ARTIFACTS_DIR="${AOT_MAF_WS_APPROVAL_ARTIFACTS_DIR:-$ROOT_DIR/artifacts/aot-maf-ws-approval}" \
APPROVAL_SMOKE_RUNTIME_MODE="aot" \
APPROVAL_SMOKE_ORCHESTRATOR="maf" \
APPROVAL_SMOKE_GATEWAY_PORT="${AOT_MAF_WS_APPROVAL_GATEWAY_PORT:-20009}" \
APPROVAL_SMOKE_PROVIDER_PORT="${AOT_MAF_WS_APPROVAL_PROVIDER_PORT:-22009}" \
APPROVAL_SMOKE_NOTE_KEY="aot-maf-approval" \
APPROVAL_SMOKE_NOTE_CONTENT="from maf aot approval" \
APPROVAL_SMOKE_PUBLISH_AOT="1" \
APPROVAL_SMOKE_ENABLE_MAF="1" \
bash "$ROOT_DIR/eng/verify-websocket-approval-smoke.sh"
