#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export HTTP_RESPONSES_FAILED_SMOKE_ARTIFACTS_DIR="${AOT_NATIVE_HTTP_RESPONSES_FAILED_ARTIFACTS_DIR:-$ROOT_DIR/artifacts/aot-native-http-responses-failed}"
export HTTP_RESPONSES_FAILED_SMOKE_RUNTIME_MODE="aot"
export HTTP_RESPONSES_FAILED_SMOKE_ORCHESTRATOR="native"
export HTTP_RESPONSES_FAILED_SMOKE_GATEWAY_PORT="${AOT_NATIVE_HTTP_RESPONSES_FAILED_GATEWAY_PORT:-20058}"
export HTTP_RESPONSES_FAILED_SMOKE_PROVIDER_PORT="${AOT_NATIVE_HTTP_RESPONSES_FAILED_PROVIDER_PORT:-22058}"
export HTTP_RESPONSES_FAILED_SMOKE_PUBLISH_AOT="1"
export HTTP_RESPONSES_FAILED_SMOKE_ENABLE_MAF="0"

bash "$ROOT_DIR/eng/verify-http-responses-failed-smoke.sh"
