#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RESTART_SMOKE_ARTIFACTS_DIR="${JIT_MAF_WS_RESTART_ARTIFACTS_DIR:-$ROOT_DIR/artifacts/jit-maf-ws-restart}" \
RESTART_SMOKE_RUNTIME_MODE="jit" \
RESTART_SMOKE_ORCHESTRATOR="maf" \
RESTART_SMOKE_GATEWAY_PORT="${JIT_MAF_WS_RESTART_GATEWAY_PORT:-20102}" \
RESTART_SMOKE_PROVIDER_PORT="${JIT_MAF_WS_RESTART_PROVIDER_PORT:-22102}" \
RESTART_SMOKE_PUBLISH_AOT="0" \
RESTART_SMOKE_ENABLE_MAF="1" \
bash "$ROOT_DIR/eng/verify-websocket-restart-resume-smoke.sh"
