#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ARTIFACTS_DIR="$ROOT_DIR/artifacts/aot-native-ws-approval-outcomes"
rm -rf "$ARTIFACTS_DIR"
mkdir -p "$ARTIFACTS_DIR"

APPROVAL_OUTCOMES_ARTIFACTS_DIR="$ARTIFACTS_DIR" \
APPROVAL_OUTCOMES_RUNTIME_MODE="aot" \
APPROVAL_OUTCOMES_ORCHESTRATOR="native" \
APPROVAL_OUTCOMES_GATEWAY_PORT="${APPROVAL_OUTCOMES_GATEWAY_PORT:-22135}" \
APPROVAL_OUTCOMES_PROVIDER_PORT="${APPROVAL_OUTCOMES_PROVIDER_PORT:-22136}" \
APPROVAL_OUTCOMES_PUBLISH_AOT=1 \
APPROVAL_OUTCOMES_ENABLE_MAF=0 \
bash "$ROOT_DIR/eng/verify-websocket-approval-outcomes-smoke.sh"
