#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export HTTP_RESPONSES_STREAM_TOOL_SMOKE_ARTIFACTS_DIR="${JIT_MAF_HTTP_RESPONSES_STREAM_TOOL_ARTIFACTS_DIR:-$ROOT_DIR/artifacts/jit-maf-http-responses-stream-tool}"
export HTTP_RESPONSES_STREAM_TOOL_SMOKE_RUNTIME_MODE="jit"
export HTTP_RESPONSES_STREAM_TOOL_SMOKE_ORCHESTRATOR="maf"
export HTTP_RESPONSES_STREAM_TOOL_SMOKE_GATEWAY_PORT="${JIT_MAF_HTTP_RESPONSES_STREAM_TOOL_GATEWAY_PORT:-20053}"
export HTTP_RESPONSES_STREAM_TOOL_SMOKE_PROVIDER_PORT="${JIT_MAF_HTTP_RESPONSES_STREAM_TOOL_PROVIDER_PORT:-22053}"
export HTTP_RESPONSES_STREAM_TOOL_SMOKE_PUBLISH_AOT="0"
export HTTP_RESPONSES_STREAM_TOOL_SMOKE_ENABLE_MAF="1"

bash "$ROOT_DIR/eng/verify-http-responses-stream-tool-smoke.sh"
