#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APPROVAL_SMOKE_ARTIFACTS_DIR="${JIT_MAF_WS_APPROVAL_ARTIFACTS_DIR:-$ROOT_DIR/artifacts/jit-maf-ws-approval}" \
APPROVAL_SMOKE_RUNTIME_MODE="jit" \
APPROVAL_SMOKE_ORCHESTRATOR="maf" \
APPROVAL_SMOKE_GATEWAY_PORT="${JIT_MAF_WS_APPROVAL_GATEWAY_PORT:-19989}" \
APPROVAL_SMOKE_PROVIDER_PORT="${JIT_MAF_WS_APPROVAL_PROVIDER_PORT:-21989}" \
APPROVAL_SMOKE_NOTE_KEY="jit-maf-approval" \
APPROVAL_SMOKE_NOTE_CONTENT="from maf jit approval" \
APPROVAL_SMOKE_PUBLISH_AOT="0" \
APPROVAL_SMOKE_ENABLE_MAF="1" \
bash "$ROOT_DIR/eng/verify-websocket-approval-smoke.sh"
