#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HTTP_PLUGIN_SMOKE_ARTIFACTS_DIR="${AOT_NATIVE_HTTP_PLUGIN_CONFIG_ARTIFACTS_DIR:-$ROOT_DIR/artifacts/aot-native-http-plugin-config}" \
HTTP_PLUGIN_SMOKE_RUNTIME_MODE="aot" \
HTTP_PLUGIN_SMOKE_ORCHESTRATOR="native" \
HTTP_PLUGIN_SMOKE_GATEWAY_PORT="${AOT_NATIVE_HTTP_PLUGIN_CONFIG_GATEWAY_PORT:-20093}" \
HTTP_PLUGIN_SMOKE_PROVIDER_PORT="${AOT_NATIVE_HTTP_PLUGIN_CONFIG_PROVIDER_PORT:-22093}" \
HTTP_PLUGIN_SMOKE_NOTE_KEY="aot-native-plugin-config" \
HTTP_PLUGIN_SMOKE_NOTE_CONTENT="from native aot plugin config" \
HTTP_PLUGIN_SMOKE_CONFIG_SOURCE="plugin_config" \
HTTP_PLUGIN_SMOKE_PUBLISH_AOT="1" \
HTTP_PLUGIN_SMOKE_ENABLE_MAF="0" \
bash "$ROOT_DIR/eng/verify-http-plugin-tool-smoke.sh"
