#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HTTP_PLUGIN_SMOKE_ARTIFACTS_DIR="${JIT_NATIVE_HTTP_PLUGIN_CONFIG_ARTIFACTS_DIR:-$ROOT_DIR/artifacts/jit-native-http-plugin-config}" \
HTTP_PLUGIN_SMOKE_RUNTIME_MODE="jit" \
HTTP_PLUGIN_SMOKE_ORCHESTRATOR="native" \
HTTP_PLUGIN_SMOKE_GATEWAY_PORT="${JIT_NATIVE_HTTP_PLUGIN_CONFIG_GATEWAY_PORT:-20091}" \
HTTP_PLUGIN_SMOKE_PROVIDER_PORT="${JIT_NATIVE_HTTP_PLUGIN_CONFIG_PROVIDER_PORT:-22091}" \
HTTP_PLUGIN_SMOKE_NOTE_KEY="jit-native-plugin-config" \
HTTP_PLUGIN_SMOKE_NOTE_CONTENT="from native jit plugin config" \
HTTP_PLUGIN_SMOKE_CONFIG_SOURCE="plugin_config" \
HTTP_PLUGIN_SMOKE_PUBLISH_AOT="0" \
HTTP_PLUGIN_SMOKE_ENABLE_MAF="0" \
bash "$ROOT_DIR/eng/verify-http-plugin-tool-smoke.sh"
