#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RESTART_SMOKE_ARTIFACTS_DIR="${AOT_MAF_WS_RESTART_ARTIFACTS_DIR:-$ROOT_DIR/artifacts/aot-maf-ws-restart}" \
RESTART_SMOKE_RUNTIME_MODE="aot" \
RESTART_SMOKE_ORCHESTRATOR="maf" \
RESTART_SMOKE_GATEWAY_PORT="${AOT_MAF_WS_RESTART_GATEWAY_PORT:-20104}" \
RESTART_SMOKE_PROVIDER_PORT="${AOT_MAF_WS_RESTART_PROVIDER_PORT:-22104}" \
RESTART_SMOKE_PUBLISH_AOT="1" \
RESTART_SMOKE_ENABLE_MAF="1" \
bash "$ROOT_DIR/eng/verify-websocket-restart-resume-smoke.sh"
