#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HTTP_PLUGIN_SMOKE_ARTIFACTS_DIR="${JIT_NATIVE_HTTP_PLUGIN_ARTIFACTS_DIR:-$ROOT_DIR/artifacts/jit-native-http-plugin}" \
HTTP_PLUGIN_SMOKE_RUNTIME_MODE="jit" \
HTTP_PLUGIN_SMOKE_ORCHESTRATOR="native" \
HTTP_PLUGIN_SMOKE_GATEWAY_PORT="${JIT_NATIVE_HTTP_PLUGIN_GATEWAY_PORT:-20019}" \
HTTP_PLUGIN_SMOKE_PROVIDER_PORT="${JIT_NATIVE_HTTP_PLUGIN_PROVIDER_PORT:-22019}" \
HTTP_PLUGIN_SMOKE_NOTE_KEY="jit-native-plugin" \
HTTP_PLUGIN_SMOKE_NOTE_CONTENT="from native jit plugin" \
HTTP_PLUGIN_SMOKE_PUBLISH_AOT="0" \
HTTP_PLUGIN_SMOKE_ENABLE_MAF="0" \
bash "$ROOT_DIR/eng/verify-http-plugin-tool-smoke.sh"
