#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HTTP_PLUGIN_SMOKE_ARTIFACTS_DIR="${JIT_MAF_HTTP_PLUGIN_ARTIFACTS_DIR:-$ROOT_DIR/artifacts/jit-maf-http-plugin}" \
HTTP_PLUGIN_SMOKE_RUNTIME_MODE="jit" \
HTTP_PLUGIN_SMOKE_ORCHESTRATOR="maf" \
HTTP_PLUGIN_SMOKE_GATEWAY_PORT="${JIT_MAF_HTTP_PLUGIN_GATEWAY_PORT:-20029}" \
HTTP_PLUGIN_SMOKE_PROVIDER_PORT="${JIT_MAF_HTTP_PLUGIN_PROVIDER_PORT:-22029}" \
HTTP_PLUGIN_SMOKE_NOTE_KEY="jit-maf-plugin" \
HTTP_PLUGIN_SMOKE_NOTE_CONTENT="from maf jit plugin" \
HTTP_PLUGIN_SMOKE_PUBLISH_AOT="0" \
HTTP_PLUGIN_SMOKE_ENABLE_MAF="1" \
bash "$ROOT_DIR/eng/verify-http-plugin-tool-smoke.sh"
