#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export HTTP_RESPONSES_FAILED_SMOKE_ARTIFACTS_DIR="${JIT_MAF_HTTP_RESPONSES_FAILED_ARTIFACTS_DIR:-$ROOT_DIR/artifacts/jit-maf-http-responses-failed}"
export HTTP_RESPONSES_FAILED_SMOKE_RUNTIME_MODE="jit"
export HTTP_RESPONSES_FAILED_SMOKE_ORCHESTRATOR="maf"
export HTTP_RESPONSES_FAILED_SMOKE_GATEWAY_PORT="${JIT_MAF_HTTP_RESPONSES_FAILED_GATEWAY_PORT:-20057}"
export HTTP_RESPONSES_FAILED_SMOKE_PROVIDER_PORT="${JIT_MAF_HTTP_RESPONSES_FAILED_PROVIDER_PORT:-22057}"
export HTTP_RESPONSES_FAILED_SMOKE_PUBLISH_AOT="0"
export HTTP_RESPONSES_FAILED_SMOKE_ENABLE_MAF="1"

bash "$ROOT_DIR/eng/verify-http-responses-failed-smoke.sh"
