#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export HTTP_RESPONSES_FAILED_SMOKE_ARTIFACTS_DIR="${JIT_NATIVE_HTTP_RESPONSES_FAILED_ARTIFACTS_DIR:-$ROOT_DIR/artifacts/jit-native-http-responses-failed}"
export HTTP_RESPONSES_FAILED_SMOKE_RUNTIME_MODE="jit"
export HTTP_RESPONSES_FAILED_SMOKE_ORCHESTRATOR="native"
export HTTP_RESPONSES_FAILED_SMOKE_GATEWAY_PORT="${JIT_NATIVE_HTTP_RESPONSES_FAILED_GATEWAY_PORT:-20056}"
export HTTP_RESPONSES_FAILED_SMOKE_PROVIDER_PORT="${JIT_NATIVE_HTTP_RESPONSES_FAILED_PROVIDER_PORT:-22056}"
export HTTP_RESPONSES_FAILED_SMOKE_PUBLISH_AOT="0"
export HTTP_RESPONSES_FAILED_SMOKE_ENABLE_MAF="0"

bash "$ROOT_DIR/eng/verify-http-responses-failed-smoke.sh"
